data:
  window_size: 5 # number of past time steps to use for prediction

  data_path: "data/data.csv"
  predictions_path: "data/predictions.csv"

training:
  batch_size: 16
  epochs: 50
  lr: 0.001

inference:
  future: 50 # number of future time steps to predict
  noise: 0.005